algorithm:
  params:
    selection:
      strategy: roulette
      elitism: true
    crossover:
      strategy: pmx
      energy: 0.4
    mutation:
      strategy: exchange
      energy: 0.01
    execution:
      population-size: 40
      generations-to-log-on-screen-interval: 50
      max-number-of-generations: 200
      stop-strategy: number_of_generations
      population-change-strategy: complete_replacement
      use-correction: true
