algorithm:
  params:
    selection:
      strategy: roulette
    crossover:
      strategy: one_point
      energy: 0.8
    fitness:
      strategy: gold
    mutation:
      strategy: simple
      energy: 0.001
    execution:
      population-size: 50
      elitism: true
      generations-to-log-on-screen-interval: 100