algorithm:
  params:
    selection:
      strategy: roulette
      elitism: true
    crossover:
      strategy: one_point
      energy: 0.8
    fitness:
      strategy: gold
    mutation:
      strategy: simple
      energy: 0.001
    execution:
      population-size: 50
      generations-to-log-on-screen-interval: 100
      max-number-of-generations: 1000000
      stop-strategy: number_of_generations
      population-change-strategy: complete_replacement